name: Publish Subtitle Player to DUFS

on:
  push:
    branches:
      - master
      - setup-new-action

jobs:
  checkout-and-publish:
    runs-on: ubuntu-latest

    env:
      PLAYER_CODE_FOLDER_NAME: subtitle_video_player
      JS_FILE_NAME: ass2srtEntry.js
      HTML_FILE_NAME: subtitle_video_player.html
      UPLOAD_FOLDER_NAME: subtitleVideoPlayer

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Publish to DUFS
        run: |
          cd ${{ env.PLAYER_CODE_FOLDER_NAME }}
          curl -T ${{ env.JS_FILE_NAME }}   ${{ vars.DUFS_BASE_URL }}/${{ env.UPLOAD_FOLDER_NAME }}/${{ env.JS_FILE_NAME }}
          curl -T ${{ env.HTML_FILE_NAME }} ${{ vars.DUFS_BASE_URL }}/${{ env.UPLOAD_FOLDER_NAME }}/${{ env.HTML_FILE_NAME }}
